chore: test path

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,26 +48,29 @@ jobs:
         run: |
           cd external/facetec-aar
           gradle publish
-
-      - name: PR Semantic Release Check
-        uses: amannn/action-semantic-pull-request@v3.1.0
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_V2 }}
-
-        with:
-          types: |
-            fix
-            feat
-            ci
-            chore
-
-      - name: Installing dependencies
+      - name: Verify that facetec-sdk was published
         run: |
-          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
-          npm ci
+          ls -R external/facetec-aar/build/repo/com/azify/facetec/facetec-sdk/9.7.47 || echo "Not found"
 
-      - name: Run build
-        run: npm run prepack
+    # - name: PR Semantic Release Check
+    #   uses: amannn/action-semantic-pull-request@v3.1.0
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN_V2 }}
 
-      - name: Run example
-        run: cd example && npm install && cd android && ./gradlew assembleRelease
+    #   with:
+    #     types: |
+    #       fix
+    #       feat
+    #       ci
+    #       chore
+
+    # - name: Installing dependencies
+    #   run: |
+    #     npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
+    #     npm ci
+
+    # - name: Run build
+    #   run: npm run prepack
+
+    # - name: Run example
+    #   run: cd example && npm install && cd android && ./gradlew assembleRelease
